<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <AvaloniaVersion>12.1.1</AvaloniaVersion>
  </PropertyGroup>
  <ItemGroup>
    <!-- Core dependencies -->
    <PackageVersion Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Markdig" Version="1.3.2" />
    <!-- Plugin dependencies -->
    <PackageVersion Include="CSharpMath.SkiaSharp" Version="0.5.1" />
    <PackageVersion Include="Mermaider" Version="0.12.2" />
    <PackageVersion Include="Svg.Controls.Skia.Avalonia" Version="12.0.0.15" />
    <PackageVersion Include="TextMateSharp" Version="2.0.4" />
    <PackageVersion Include="TextMateSharp.Grammars" Version="2.0.4" />
    <!-- Samples dependencies -->
    <PackageVersion Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <!-- Test dependencies -->
    <PackageVersion Include="Avalonia.Headless.XUnit" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.10.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>
</Project>