<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RuntimeIdentifiers>linux-x64;osx-arm64;win-x64</RuntimeIdentifiers>
  </PropertyGroup>
  <PropertyGroup>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>true</PublishTrimmed>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <EnableAotAnalyzer>true</EnableAotAnalyzer>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../MarkView.Avalonia.Demo/MarkView.Avalonia.Demo.csproj" />
  </ItemGroup>
</Project>
